name: Jest Tests

on:
    push:
        branches:
            - main # Or your default branch
    pull_request:
        branches:
            - main # Or your default branch

jobs:
    run-jest-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # Use the latest version

            - name: Setup Node.js
              uses: actions/setup-node@v4 # Use the latest version
              with:
                  node-version: "22.14.0" # Specify your desired Node.js version

            - name: Install dependencies
              run: npm ci # Use npm ci for clean installations in CI

            - name: Run Jest tests
              run: npm test
